version: "2"
services:
  forecasting_service:
    build: forecasting_service
    container_name: "forecasting_service"
    ports:
      - "8080:8080"
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
      - influxdb
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_USER="user"
        - MONGODB_PASS="pass"
      volumes:
        - ./data/db:/data/db
      ports:
          - "27017:27017"
      command: mongod --smallfiles --logpath=/dev/null --auth # --quiet
  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    links:
      - influxdb